In [10]:
import numpy as np
array = np.random.randint(1,21,size =( 5,5))
print(f"original array")
print(array)

#replace the 3 coloumn with 1 
array[:,2]=1
print("modified array")
print(array)


original array
[[ 2  4 17 13 20]
 [ 8  7 16 14 14]
 [19 11  9  7 13]
 [ 7 15  1  8 13]
 [20 11  9 19  9]]
modified array
[[ 2  4  1 13 20]
 [ 8  7  1 14 14]
 [19 11  1  7 13]
 [ 7 15  1  8 13]
 [20 11  1 19  9]]


In [2]:
import numpy as np
array = np.arange(1,17).reshape((4,4))
print("original array")
print(array)

#lets replace the array with 0

np.fill_diagonal(array,0)
print("modified array")
print(array)

original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
modified array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [3]:
import numpy as np
array = np.arange(1,37).reshape((6,6))
print("original array")
print(array)

sub_array = array[2:5,1:5]
print("modified array")
print(array)

original array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
modified array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [10]:
array = np.random.randint(1,21,size=(5,5))
print("original array")
print(array)

border_element = np.concatenate((array[0,:],array[-1,:],array[1:-1,0],array[1:-1,1]))
print("border elements")
print(border_element)

original array
[[19 18 16  1 12]
 [ 6 12 13  2 11]
 [ 6  7 10 13 15]
 [16  9 18  2 13]
 [ 5 15  9 20 11]]
border elements
[19 18 16  1 12  5 15  9 20 11  6  6 16 12  7  9]


In [17]:
array1 = np.random.randint(1,11,size=(3,4))
array2 = np.random.randint(1,11,size=(3,4))
print("original 1st array")
print(array1)
print("original 2nd array")
print(array2)

addition = array1 + array2
print(addition)
substraction = array1 - array2
print(substraction)
multiplication = array1 * array2
print(multiplication)
divition = array1 / array2
print(divition)

original 1st array
[[ 1  8 10  6]
 [ 5  8  2  3]
 [ 3  6  2  2]]
original 2nd array
[[5 6 7 4]
 [7 9 1 5]
 [3 7 6 2]]
[[ 6 14 17 10]
 [12 17  3  8]
 [ 6 13  8  4]]
[[-4  2  3  2]
 [-2 -1  1 -2]
 [ 0 -1 -4  0]]
[[ 5 48 70 24]
 [35 72  2 15]
 [ 9 42 12  4]]
[[0.2        1.33333333 1.42857143 1.5       ]
 [0.71428571 0.88888889 2.         0.6       ]
 [1.         0.85714286 0.33333333 1.        ]]


In [18]:
array = np.random.randint(1,11,size=(4,5))
print("original array")
print(array)
row_wise_sum = np.sum(array,axis=1)
print(row_wise_sum)
coloumn_wise_sum=np.sum(array,axis=0)
print(coloumn_wise_sum)

original array
[[ 8  5  9  3  4]
 [ 8 10  7  1  5]
 [ 2  2  6 10  1]
 [ 6  2  2  8  8]]
[29 31 21 26]
[24 19 24 22 18]


In [23]:
array = np.random.randint(1,11,size=(4,5))
print("original array")
print(array)

mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print(f'mean {mean}')
print(f"median{median}")
print(f"std_dev{std_dev}")
print(f'variamce{variance}')

original array
[[10  5  6  7  8]
 [ 6  1  5  9  4]
 [ 8  5  8  1  6]
 [ 1  4  6 10  2]]
mean 5.6
median6.0
std_dev2.764054992217051
variamce7.640000000000001


In [25]:
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [5]:
import numpy as np
array = np.random.randint(1,11,size=(3,3))
row_array = np.random.randint(1,11,size=(3,))
print("original array")
print(array)
print("1D array")
print(row_array)
result = array+row_array
print(result)

original array
[[7 9 1]
 [1 7 8]
 [5 4 3]]
1D array
[ 8 10  9]
[[15 19 10]
 [ 9 17 17]
 [13 14 12]]


In [7]:
array = np.random.randint(1,11,size=(4,4))
row_array = np.random.randint(1,11,size=(4,))
print("original array")
print(array)
print(row_array)
result = array - row_array
print(result)

original array
[[ 4  1 10  3]
 [ 5  1  2  3]
 [ 4  8 10  7]
 [ 4  8  7  3]]
[ 6  7  2 10]
[[-2 -6  8 -7]
 [-1 -6  0 -7]
 [-2  1  8 -3]
 [-2  1  5 -7]]


In [9]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[10  1 10]
 [ 2  6  3]
 [ 1  3  1]]
Determinant: -29.000000000000018
Inverse:
[[ 0.10344828 -1.          1.96551724]
 [-0.03448276  0.          0.34482759]
 [-0.          1.         -2.        ]]
Eigenvalues: [12.36054732  5.09952934 -0.46007666]


In [11]:
array1 = np.random.randint(1,11,size=(2,3))
array2 = np.random.randint(1,11,size=(3,2))
print("original array1")
print(array1)
print("original array2")
print(array2)
result = np.dot(array1,array2)
print(result)

original array1
[[ 4 10  8]
 [ 3  4  1]]
original array2
[[6 1]
 [3 6]
 [8 9]]
[[118 136]
 [ 38  36]]


In [13]:
array1 = np.random.randint(1,9,size=(3,3))
print("original array")
print(array1)
array_reshape = array1.reshape(1,9)
print(array_reshape)
array_reshape2 = array_reshape.reshape(9,1)
print(array_reshape2)

original array
[[7 3 3]
 [5 6 4]
 [1 2 7]]
[[7 3 3 5 6 4 1 2 7]]
[[7]
 [3]
 [3]
 [5]
 [6]
 [4]
 [1]
 [2]
 [7]]


In [23]:
array = np.random.randint(1,9,size=(5,5))
print("original array")
print(array)
flatten_array = array.flatten()
print(flatten_array)
reshape_array = flatten_array.reshape((5,5))
print(reshape_array)

original array
[[4 1 5 3 4]
 [3 6 2 2 8]
 [6 7 7 1 4]
 [8 5 6 3 1]
 [7 6 5 2 8]]
[4 1 5 3 4 3 6 2 2 8 6 7 7 1 4 8 5 6 3 1 7 6 5 2 8]
[[4 1 5 3 4]
 [3 6 2 2 8]
 [6 7 7 1 4]
 [8 5 6 3 1]
 [7 6 5 2 8]]


In [28]:
arrat = np.random.randint(1,21,size=(5,5))
print("original array")
print(arrat)
corners = arrat[[0,0,-1,-1],[0,-1,0,-1]]
print(corners)

original array
[[ 5  6  7 13  3]
 [11 10  9 11 10]
 [16  7 20  1 13]
 [20 11  7  9 10]
 [ 6  4 10 14 19]]
[ 5  3  6 19]


In [33]:
array = np.random.randint(1,21,size=(5,5))
print("original array")
print(array)
array[array>10]=10
print(array)

original array
[[ 1 19  6  5  1]
 [17  6 15  1 19]
 [20  2 20 13 15]
 [19 11  6 12  9]
 [19 14 17  9  1]]
[[ 1 10  6  5  1]
 [10  6 10  1 10]
 [10  2 10 10 10]
 [10 10  6 10  9]
 [10 10 10  9  1]]
